


services:
    db:
        image: mariadb:10.5.6
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        volumes:
            - ./data:/var/lib/mysql

    app:
        image: alpine:0.2
        depends_on:
            - db
        volumes:
            - ./:/var/www/html/

    nginx:
        image: alpine:0.2
        depends_on:
            - app
        volumes:
            - ./:/usr/share/nginx/html
        ports:
            - 8080:80